// ==============================================================================
// JUBILANT METAL AND ALLOYS - REALISTIC B2B SAMPLE & SEED DATA
// ==============================================================================

import {
  CompanyProfile,
  ProductCategory,
  Product,
  Customer,
  BankAccount,
  TermsTemplate,
  QuotationSettings,
  Quotation,
  User,
} from '../types';

export const INITIAL_COMPANY: CompanyProfile = {
  id: 'comp-jubilant-01',
  name: 'JUBILANT METAL AND ALLOYS',
  tagline: 'Stockist, Manufacturer & Global Exporters of High Nickel Alloys, Stainless Steel & Pipes',
  logo: '/New logo.png',
  gstin: '27AABCJ4589K1Z5',
  pan: 'AABCJ4589K',
  cin: 'U27100MH2012PTC231456',
  addressLine1: 'Plot No. C-14/2, Taloja Industrial Area, MIDC',
  addressLine2: 'Navi Mumbai, Raigad District',
  city: 'Navi Mumbai',
  state: 'Maharashtra',
  stateCode: '27',
  country: 'India',
  pinCode: '410208',
  phone: '+91 22 2741 8900 / +91 98201 45890',
  email: 'sales@jubilantmetal.com',
  website: 'www.jubilantmetal.com',
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-01',
    name: 'Rajesh Sharma',
    email: 'admin@jubilantmetal.com',
    role: 'admin',
    phone: '+91 98201 45890',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-02',
    name: 'Vikram Mehta',
    email: 'vikram.m@jubilantmetal.com',
    role: 'sales_manager',
    phone: '+91 98202 33411',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2026-01-15T11:30:00Z',
  },
  {
    id: 'user-03',
    name: 'Anjali Desai',
    email: 'anjali.d@jubilantmetal.com',
    role: 'sales_executive',
    phone: '+91 98203 77890',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'user-04',
    name: 'Amit Patel',
    email: 'viewer@jubilantmetal.com',
    role: 'viewer',
    phone: '+91 98204 11223',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2026-02-15T14:20:00Z',
  },
];

export const INITIAL_CATEGORIES: ProductCategory[] = [
  { id: 'cat-01', name: 'Pipes & Tubes', slug: 'pipes-tubes', description: 'Seamless & Welded Pipes, Heat Exchanger & Instrumentation Tubes', icon: 'Pipette', isActive: true, itemCount: 5 },
  { id: 'cat-02', name: 'Plates & Sheets', slug: 'plates-sheets', description: 'Hot Rolled, Cold Rolled, Shim Sheets & Chequered Plates', icon: 'Layers', isActive: true, itemCount: 3 },
  { id: 'cat-03', name: 'Bars & Rods', slug: 'bars-rods', description: 'Round, Square, Hex, Bright & Forged Steel/Alloy Bars', icon: 'Minimize2', isActive: true, itemCount: 3 },
  { id: 'cat-04', name: 'Flanges', slug: 'flanges', description: 'WNRF, Blind, Slip-On, Socket Weld & Lap Joint Flanges', icon: 'Disc', isActive: true, itemCount: 2 },
  { id: 'cat-05', name: 'Butt Weld Fittings', slug: 'butt-weld-fittings', description: 'Elbows, Tees, Reducers, Caps & Stub Ends ASME B16.9', icon: 'GitCommit', isActive: true, itemCount: 2 },
  { id: 'cat-06', name: 'Forged Fittings', slug: 'forged-fittings', description: 'Class 3000/6000 Socket Weld & Threaded Fittings ASME B16.11', icon: 'Maximize2', isActive: true, itemCount: 2 },
  { id: 'cat-07', name: 'Fasteners', slug: 'fasteners', description: 'High Tensile & Stainless Stud Bolts, Heavy Hex Nuts & Washers', icon: 'Settings2', isActive: true, itemCount: 1 },
  { id: 'cat-08', name: 'Valves & Instrumentation', slug: 'valves', description: 'Ball, Gate, Globe, Check Valves & Manifolds', icon: 'Sliders', isActive: true, itemCount: 1 },
  { id: 'cat-09', name: 'Dairy & Pharma Fittings', slug: 'dairy-pharma', description: 'Tri-Clamp, SMS Unions, Sanitary Bends with 0.4 Ra Mirror Finish', icon: 'Sparkles', isActive: true, itemCount: 1 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    productCode: 'JMA-PIP-316L-01',
    name: 'SS 316L Seamless Pipe',
    categoryId: 'cat-01',
    categoryName: 'Pipes & Tubes',
    subcategory: 'Seamless Pipes',
    material: 'Stainless Steel',
    grade: 'ASTM A312 TP316L',
    size: '2" NB (60.3 mm OD)',
    od: '60.3 mm',
    idDim: '52.5 mm',
    thickness: '3.91 mm',
    schedule: 'SCH 40',
    length: '6 MTR (Standard Length)',
    standard: 'ASTM A312 / ASME SA312',
    specification: 'Solution Annealed & Pickled, Hydrotested & NDT Passed',
    finish: 'Mill Finish / Pickled',
    form: 'Seamless',
    unit: 'MTR',
    hsnCode: '73044100',
    gstRate: 18,
    defaultSellingPrice: 1450,
    description: 'High corrosion resistance seamless pipe suitable for chemical and petrochemical transfer lines.',
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'prod-02',
    productCode: 'JMA-PIP-304-02',
    name: 'SS 304 Welded Pipe',
    categoryId: 'cat-01',
    categoryName: 'Pipes & Tubes',
    subcategory: 'Welded Pipes',
    material: 'Stainless Steel',
    grade: 'ASTM A312 TP304',
    size: '4" NB (114.3 mm OD)',
    od: '114.3 mm',
    idDim: '108.2 mm',
    thickness: '3.05 mm',
    schedule: 'SCH 10S',
    length: '6 MTR',
    standard: 'ASTM A312 / ASTM A358',
    specification: 'TIG / Plasma Welded, 100% Radiography Class 1',
    finish: 'Pickled & Passivated',
    form: 'Welded (ERW)',
    unit: 'MTR',
    hsnCode: '73064000',
    gstRate: 18,
    defaultSellingPrice: 2150,
    description: 'Austenitic SS welded pipe for industrial water, air and low-pressure piping networks.',
    isActive: true,
    createdAt: '2026-01-16T10:00:00Z',
    updatedAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'prod-03',
    productCode: 'JMA-PIP-DUP-03',
    name: 'Super Duplex 2507 Seamless Pipe',
    categoryId: 'cat-01',
    categoryName: 'Pipes & Tubes',
    subcategory: 'Duplex & Super Duplex',
    material: 'Super Duplex Stainless Steel',
    grade: 'UNS S32750 / 2507',
    size: '3" NB (88.9 mm OD)',
    od: '88.9 mm',
    idDim: '77.9 mm',
    thickness: '5.49 mm',
    schedule: 'SCH 40S',
    length: '5.8 - 6.0 MTR',
    standard: 'ASTM A790 / ASME SA790',
    specification: 'Solution Annealed, PREN > 42, Pitting & Stress Corrosion Cracking Resistant',
    finish: 'Bright Annealed / Pickled',
    form: 'Seamless',
    unit: 'MTR',
    hsnCode: '73044100',
    gstRate: 18,
    defaultSellingPrice: 6200,
    description: 'Exceptional strength and chloride resistance for offshore oil rigs and desalination plants.',
    isActive: true,
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'prod-04',
    productCode: 'JMA-PIP-INC-04',
    name: 'Inconel 625 Seamless Tube',
    categoryId: 'cat-01',
    categoryName: 'Pipes & Tubes',
    subcategory: 'Nickel Alloys',
    material: 'Nickel Alloy (Inconel)',
    grade: 'Inconel 625 (UNS N06625)',
    size: '1/2" OD (12.7 mm OD)',
    od: '12.7 mm',
    thickness: '1.24 mm',
    schedule: '18 SWG',
    length: '6 MTR Straight',
    standard: 'ASTM B444 / ASME SB444',
    specification: 'Grade 1 Annealed, 100% Eddy Current Tested',
    finish: 'Cold Drawn Bright Annealed',
    form: 'Seamless',
    unit: 'MTR',
    hsnCode: '75071200',
    gstRate: 18,
    defaultSellingPrice: 3850,
    description: 'High temperature oxidation and fatigue resistant instrumentation tubing for aerospace & naval use.',
    isActive: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-05',
    productCode: 'JMA-PIP-CS-05',
    name: 'Carbon Steel Seamless Pipe A106 Gr. B',
    categoryId: 'cat-01',
    categoryName: 'Pipes & Tubes',
    subcategory: 'Carbon Steel',
    material: 'Carbon Steel',
    grade: 'ASTM A106 Grade B',
    size: '6" NB (168.3 mm OD)',
    od: '168.3 mm',
    thickness: '7.11 mm',
    schedule: 'SCH 40',
    length: '6 MTR Random',
    standard: 'ASTM A106 / ASME SA106 / API 5L Gr. B',
    specification: 'High temperature service, IBR Approved with Form III-A Certificate',
    finish: 'Black Varnished / Bare',
    form: 'Seamless',
    unit: 'MTR',
    hsnCode: '73041910',
    gstRate: 18,
    defaultSellingPrice: 1950,
    description: 'IBR certified carbon steel seamless pipe for boilers, power plants, and high-pressure steam.',
    isActive: true,
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: 'prod-06',
    productCode: 'JMA-PLT-304-06',
    name: 'SS 304 Hot Rolled Industrial Plate',
    categoryId: 'cat-02',
    categoryName: 'Plates & Sheets',
    subcategory: 'Plates',
    material: 'Stainless Steel',
    grade: 'ASTM A240 TP304',
    size: '1500 mm × 6000 mm',
    thickness: '10 mm',
    length: '6000 mm',
    width: '1500 mm',
    standard: 'ASTM A240 / ASME SA240',
    specification: 'No. 1 Finish, Descaled, MTC according to EN 10204 3.1',
    finish: 'No. 1 (Hot Rolled, Annealed & Pickled)',
    form: 'Hot Rolled Plate',
    unit: 'KG',
    hsnCode: '72192100',
    gstRate: 18,
    defaultSellingPrice: 245,
    description: 'Prime quality heavy stainless plate for storage tanks, pressure vessels and fabrication.',
    isActive: true,
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'prod-07',
    productCode: 'JMA-PLT-316L-07',
    name: 'SS 316L Cold Rolled Sheet 2B',
    categoryId: 'cat-02',
    categoryName: 'Plates & Sheets',
    subcategory: 'Sheets',
    material: 'Stainless Steel',
    grade: 'ASTM A240 TP316L',
    size: '1250 mm × 2500 mm',
    thickness: '2.0 mm',
    length: '2500 mm',
    width: '1250 mm',
    standard: 'ASTM A240 / EN 10088-2',
    specification: '2B smooth finish with PVC protective coating film on one side',
    finish: '2B Finish with Laser Film',
    form: 'Cold Rolled Sheet',
    unit: 'KG',
    hsnCode: '72193300',
    gstRate: 18,
    defaultSellingPrice: 340,
    description: 'Precision cold-rolled sheet for pharmaceutical equipment, food processing, and architectural panels.',
    isActive: true,
    createdAt: '2026-01-27T10:00:00Z',
    updatedAt: '2026-01-27T10:00:00Z',
  },
  {
    id: 'prod-08',
    productCode: 'JMA-PLT-MON-08',
    name: 'Monel 400 Corrosion Resistant Plate',
    categoryId: 'cat-02',
    categoryName: 'Plates & Sheets',
    subcategory: 'Nickel Alloys',
    material: 'Nickel-Copper Alloy (Monel)',
    grade: 'Monel 400 (UNS N04400)',
    size: '1000 mm × 2000 mm',
    thickness: '6.0 mm',
    length: '2000 mm',
    width: '1000 mm',
    standard: 'ASTM B127 / ASME SB127',
    specification: 'Hot Rolled, Annealed & Pickled, resistant to seawater, hydrofluoric acid and alkalis',
    finish: 'Pickled Mill Finish',
    form: 'Plate',
    unit: 'KG',
    hsnCode: '75061000',
    gstRate: 18,
    defaultSellingPrice: 2850,
    description: 'Marine and chemical industry nickel alloy plate with superior resistance to rapid flowing seawater.',
    isActive: true,
    createdAt: '2026-01-29T10:00:00Z',
    updatedAt: '2026-01-29T10:00:00Z',
  },
  {
    id: 'prod-09',
    productCode: 'JMA-BAR-316-09',
    name: 'SS 316 Bright Round Bar',
    categoryId: 'cat-03',
    categoryName: 'Bars & Rods',
    subcategory: 'Round Bars',
    material: 'Stainless Steel',
    grade: 'AISI 316 / ASTM A276',
    size: '50 mm Dia',
    od: '50 mm',
    length: '3 to 6 MTR',
    standard: 'ASTM A276 / ASTM A479',
    specification: 'Cold Drawn, Centerless Ground & Polished, h9 Tolerance',
    finish: 'Bright Polished / h9',
    form: 'Bright Round Bar',
    unit: 'KG',
    hsnCode: '72222010',
    gstRate: 18,
    defaultSellingPrice: 320,
    description: 'Precision engineered SS 316 round bar for pump shafts, valves, and precision CNC components.',
    isActive: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod-10',
    productCode: 'JMA-BAR-INC-10',
    name: 'Inconel 718 High Strength Round Bar',
    categoryId: 'cat-03',
    categoryName: 'Bars & Rods',
    subcategory: 'Nickel Alloys',
    material: 'Nickel-Chromium Alloy',
    grade: 'Inconel 718 (UNS N07718)',
    size: '75 mm Dia',
    od: '75 mm',
    length: '2 to 4 MTR',
    standard: 'ASTM B637 / AMS 5662 / AMS 5663',
    specification: 'Precipitation Hardened, Solution Annealed, Ultrasonic Tested to AMS 2631',
    finish: 'Peeled & Polished',
    form: 'Forged & Turned Bar',
    unit: 'KG',
    hsnCode: '75051200',
    gstRate: 18,
    defaultSellingPrice: 4200,
    description: 'High-strength, corrosion-resistant nickel chromium bar for gas turbines, rocket motors, and downhole tools.',
    isActive: true,
    createdAt: '2026-02-03T10:00:00Z',
    updatedAt: '2026-02-03T10:00:00Z',
  },
  {
    id: 'prod-11',
    productCode: 'JMA-BAR-DUP-11',
    name: 'Duplex 2205 Round Bar',
    categoryId: 'cat-03',
    categoryName: 'Bars & Rods',
    subcategory: 'Duplex Steel',
    material: 'Duplex Stainless Steel',
    grade: 'UNS S32205 / F51 / 1.4462',
    size: '100 mm Dia',
    od: '100 mm',
    length: '3 to 5 MTR',
    standard: 'ASTM A276 / ASTM A479',
    specification: 'Hot Forged, Annealed and Rough Turned, Tested for Charpy Impact at -46°C',
    finish: 'Rough Turned',
    form: 'Forged Bar',
    unit: 'KG',
    hsnCode: '72221100',
    gstRate: 18,
    defaultSellingPrice: 510,
    description: 'High mechanical yield strength combined with high pitting resistance for subsea equipment.',
    isActive: true,
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'prod-12',
    productCode: 'JMA-FLG-316-12',
    name: 'SS 316 Weld Neck Flange (WNRF)',
    categoryId: 'cat-04',
    categoryName: 'Flanges',
    subcategory: 'Weld Neck Flanges',
    material: 'Stainless Steel',
    grade: 'ASTM A182 F316',
    size: '3" NB (Class 150)',
    schedule: 'SCH 40',
    classRating: 'Class 150',
    pressureRating: '150 LBS',
    standard: 'ASME B16.5',
    specification: 'Forged, Serrated Raised Face 125-250 AARH finish',
    finish: 'Machined & Serrated',
    form: 'Forged Flange',
    unit: 'PCS',
    hsnCode: '73072100',
    gstRate: 18,
    defaultSellingPrice: 2850,
    description: 'Precision forged weld neck flange for high-integrity piping systems.',
    isActive: true,
    createdAt: '2026-02-07T10:00:00Z',
    updatedAt: '2026-02-07T10:00:00Z',
  },
  {
    id: 'prod-13',
    productCode: 'JMA-FLG-DUP-13',
    name: 'Super Duplex 2507 Blind Flange (BLRF)',
    categoryId: 'cat-04',
    categoryName: 'Flanges',
    subcategory: 'Blind Flanges',
    material: 'Super Duplex Steel',
    grade: 'ASTM A182 F53 (UNS S32750)',
    size: '4" NB (Class 300)',
    classRating: 'Class 300',
    pressureRating: '300 LBS',
    standard: 'ASME B16.5',
    specification: 'Solution Treated & Water Quenched, NACE MR0175 compliant',
    finish: 'Serrated RF 125-250 RMS',
    form: 'Forged',
    unit: 'PCS',
    hsnCode: '73072100',
    gstRate: 18,
    defaultSellingPrice: 9400,
    description: 'Heavy duty super duplex blind flange designed for offshore choke and kill manifolds.',
    isActive: true,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'prod-14',
    productCode: 'JMA-FIT-BW-14',
    name: 'SS 316L Butt Weld 90° Elbow Long Radius',
    categoryId: 'cat-05',
    categoryName: 'Butt Weld Fittings',
    subcategory: 'Elbows',
    material: 'Stainless Steel',
    grade: 'ASTM A403 WP316L',
    size: '2" NB',
    schedule: 'SCH 40',
    thickness: '3.91 mm',
    standard: 'ASME B16.9',
    specification: 'Seamless Construction, Bevelled Ends to ASME B16.25, 100% PMI verified',
    finish: 'Pickled & Passivated',
    form: 'Seamless',
    unit: 'PCS',
    hsnCode: '73072300',
    gstRate: 18,
    defaultSellingPrice: 780,
    description: 'Seamless stainless butt weld elbow for direction change in piping with minimal pressure drop.',
    isActive: true,
    createdAt: '2026-02-12T10:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    id: 'prod-15',
    productCode: 'JMA-FIT-BW-15',
    name: 'Hastelloy C276 Equal Tee',
    categoryId: 'cat-05',
    categoryName: 'Butt Weld Fittings',
    subcategory: 'Tees',
    material: 'Nickel Alloy (Hastelloy)',
    grade: 'ASTM B366 WPHC276 (UNS N10276)',
    size: '3" NB',
    schedule: 'SCH 40',
    thickness: '5.49 mm',
    standard: 'ASME B16.9',
    specification: 'Formed from seamless pipe, Annealed, NACE MR0175 compliant',
    finish: 'Bright Pickled',
    form: 'Seamless',
    unit: 'PCS',
    hsnCode: '75072000',
    gstRate: 18,
    defaultSellingPrice: 14500,
    description: 'Extreme resistance to wet chlorine gas, hypochlorite and chlorine dioxide in aggressive processes.',
    isActive: true,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'prod-16',
    productCode: 'JMA-FIT-FRG-16',
    name: 'Alloy Steel A182 F11 Socket Weld Union',
    categoryId: 'cat-06',
    categoryName: 'Forged Fittings',
    subcategory: 'Unions',
    material: 'Alloy Steel (Chrome Moly)',
    grade: 'ASTM A182 Grade F11 Class 2',
    size: '1" NB',
    classRating: 'Class 3000',
    pressureRating: '3000 PSI',
    standard: 'ASME B16.11 / MSS-SP-83',
    specification: 'Integral ground ball joint seat, IBR approved with IBR Form III-C',
    finish: 'Rust Proof Oil Coated',
    form: 'Forged',
    unit: 'PCS',
    hsnCode: '73079910',
    gstRate: 18,
    defaultSellingPrice: 1350,
    description: 'High-temperature chrome-moly union for thermal power stations and petrochemical piping.',
    isActive: true,
    createdAt: '2026-02-16T10:00:00Z',
    updatedAt: '2026-02-16T10:00:00Z',
  },
  {
    id: 'prod-17',
    productCode: 'JMA-FIT-FRG-17',
    name: 'SS 316L Threaded NPT Hex Nipple',
    categoryId: 'cat-06',
    categoryName: 'Forged Fittings',
    subcategory: 'Nipples',
    material: 'Stainless Steel',
    grade: 'ASTM A182 F316L',
    size: '1/2" NPT Male × 1/2" NPT Male',
    classRating: 'Class 3000',
    pressureRating: '3000 PSI',
    standard: 'ASME B16.11 / BS 3799',
    specification: 'Clean machined NPT threads according to ASME B1.20.1',
    finish: 'Machined Bright',
    form: 'Barstock / Forged',
    unit: 'PCS',
    hsnCode: '73072900',
    gstRate: 18,
    defaultSellingPrice: 280,
    description: 'Precision threaded hex nipple for instrumentation tubing manifolds and gauge connections.',
    isActive: true,
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'prod-18',
    productCode: 'JMA-FAS-B8M-18',
    name: 'SS 316 Stud Bolt with 2 Heavy Hex Nuts',
    categoryId: 'cat-07',
    categoryName: 'Fasteners',
    subcategory: 'Stud Bolts',
    material: 'Stainless Steel',
    grade: 'ASTM A193 B8M (Bolt) / ASTM A194 Gr. 8M (Nuts)',
    size: '5/8" UNC × 90 mm Length',
    length: '90 mm',
    standard: 'ASME B18.31.2 / ASME B18.2.2',
    specification: 'Class 1 Solution Treated, Full Threaded, High Creep & Tensile Strength',
    finish: 'Bright Cleaned / Passivated',
    form: 'Machined',
    unit: 'SET',
    hsnCode: '73181500',
    gstRate: 18,
    defaultSellingPrice: 190,
    description: 'Standard piping flange bolting set for acidic and marine operating environments.',
    isActive: true,
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'prod-19',
    productCode: 'JMA-VLV-BAL-19',
    name: 'SS 316 3-Piece Ball Valve Class 800',
    categoryId: 'cat-08',
    categoryName: 'Valves & Instrumentation',
    subcategory: 'Ball Valves',
    material: 'Stainless Steel CF8M / SS 316',
    grade: 'ASTM A351 CF8M / Barstock SS316',
    size: '1" NB (25 mm)',
    classRating: 'Class 800',
    pressureRating: '800 WOG',
    standard: 'BS 5351 / API 6D / ASME B16.34',
    specification: 'Full Bore, PTFE/RPTFE Seats, Blowout-Proof Stem, Fire-Safe Design to API 607',
    finish: 'Investment Cast & Electropolished',
    form: 'Cast / Machined',
    unit: 'PCS',
    hsnCode: '84818030',
    gstRate: 18,
    defaultSellingPrice: 3450,
    description: 'Heavy duty quarter-turn isolation ball valve for high-cycle process applications.',
    isActive: true,
    createdAt: '2026-02-22T10:00:00Z',
    updatedAt: '2026-02-22T10:00:00Z',
  },
  {
    id: 'prod-20',
    productCode: 'JMA-SAN-TC-20',
    name: 'Sanitary Tri-Clamp Ferrule & Clamp Set',
    categoryId: 'cat-09',
    categoryName: 'Dairy & Pharma Fittings',
    subcategory: 'Tri-Clamp Ferrules',
    material: 'Stainless Steel',
    grade: 'ASTM A270 TP316L',
    size: '1.5" (38.1 mm OD)',
    standard: 'DIN 32676 / ISO 2852 / 3A Sanitary',
    specification: 'Internal surface electropolished to Ra ≤ 0.4 µm, silicone food-grade gasket included',
    finish: 'Mirror Polished Ra < 0.4 um',
    form: 'Forged & Precision CNC Machined',
    unit: 'SET',
    hsnCode: '73072900',
    gstRate: 18,
    defaultSellingPrice: 820,
    description: 'Ultra-hygienic connection ferrule for injectable pharmaceutical and food processing lines.',
    isActive: true,
    createdAt: '2026-02-24T10:00:00Z',
    updatedAt: '2026-02-24T10:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-demo-01',
    customerCode: 'CUST-DEMO-01',
    companyName: 'Demo Engineering Corporation Pvt Ltd',
    contactPerson: 'Sanjay Deshmukh',
    designation: 'Head of Procurement & Materials',
    email: 'purchase@demoengineering.com',
    phone: '+91 22 6705 4000',
    whatsapp: '+91 98200 12345',
    gstin: '27AABCD1234E1Z5',
    pan: 'AABCD1234E',
    billingAddress: 'Plot No. 101, Industrial Corridor, MIDC',
    shippingAddress: 'Plot No. 101, Industrial Corridor, MIDC',
    city: 'Mumbai',
    state: 'Maharashtra',
    stateCode: '27',
    country: 'India',
    pinCode: '400001',
    paymentTerms: '30 Days Net',
    creditLimit: 5000000,
    notes: 'Single demo client company retained for test quotation generation.',
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank-01',
    bankName: 'HDFC Bank Limited',
    accountName: 'JUBILANT METAL AND ALLOYS',
    accountNumber: '50200045892144',
    ifscCode: 'HDFC0001024',
    branchName: 'MIDC Industrial Branch, Taloja, Navi Mumbai',
    upiId: 'jubilantmetal@hdfcbank',
    swiftCode: 'HDFCINBBXXX',
    isDefault: true,
  },
  {
    id: 'bank-02',
    bankName: 'State Bank of India',
    accountName: 'JUBILANT METAL AND ALLOYS',
    accountNumber: '39485729104',
    ifscCode: 'SBIN0004521',
    branchName: 'Commercial Branch, Fort, Mumbai',
    upiId: 'jubilantmetal@sbi',
    swiftCode: 'SBININBB214',
    isDefault: false,
  },
];

export const INITIAL_TERMS_TEMPLATES: TermsTemplate[] = [
  {
    id: 'terms-01',
    title: 'Standard Metal Supply Terms & Conditions',
    isDefault: true,
    terms: [
      'PRICE BASIS: Ex-works Taloja / Kalamboli Godown, Navi Mumbai, excluding freight and transit insurance unless specified.',
      'TAXES & DUTIES: GST as applicable at the prevailing government rates (18% standard for base metal & steel products). Any change in statutory levies shall be on buyer’s account.',
      'DELIVERY PERIOD: Materials ex-stock subject to prior sale. For manufacturing items, 2 to 4 weeks from technical and commercial confirmation of Purchase Order.',
      'INSPECTION & TESTING: Material Test Certificate (MTC) will be provided with supply as per EN 10204 Type 3.1. Third-party inspection (TPI) by agencies like Lloyd’s, TUV, Bureau Veritas or DNV can be arranged at nominal extra cost.',
      'PAYMENT TERMS: 100% against Proforma Invoice prior to dispatch, or mutually agreed credit terms against accepted PO.',
      'VALIDITY: This quotation is valid for 15 days from quotation date due to global London Metal Exchange (LME) raw material price fluctuations.',
      'WARRANTY: 12 months from installation or 18 months from supply against defects in workmanship or non-conformance to stated international standards.',
      'JURISDICTION: Any dispute arising out of this contract shall be subject to the exclusive jurisdiction of the competent courts in Mumbai, India.',
    ],
  },
  {
    id: 'terms-02',
    title: 'High-Nickel Alloys & Fast-Track Project Terms',
    isDefault: false,
    terms: [
      'SPECIAL ALLOY SURCHARGE: Raw material prices for Inconel, Monel, and Hastelloy are indexed to LME and subject to revision after 7 calendar days.',
      'POSITIVE MATERIAL IDENTIFICATION: 100% PMI testing with handheld XRF analyzer will be conducted and detailed PMI certificate provided.',
      'PACKAGING: Seaworthy / export wooden boxes with plastic wrapping and rust-preventive coating.',
      'PAYMENT: 20% advance with Purchase Order, 80% balance against inspection and dispatch clearance.',
      'CANCELLATION: Special alloy cut-to-size items cannot be cancelled once cutting or fabrication commences.',
    ],
  },
];

export const INITIAL_SETTINGS: QuotationSettings = {
  prefix: 'JMA',
  currentYear: 2026,
  sequenceNumber: 1001,
  formatTemplate: '{PREFIX}-{YEAR}-{NUMBER}',
  defaultValidityDays: 15,
  defaultCurrency: 'INR',
  defaultCurrencySymbol: '₹',
  defaultPaymentTerms: '100% against Proforma Invoice / Dispatch',
  defaultDeliveryTerms: 'Ex-Works, Mumbai / Taloja Godown',
  signatureUrl: '/signature.png',
  stampUrl: '/stamp.png',
  signatureEnabled: true,
  stampEnabled: true,
  signatureSize: 'md',
  stampSize: 'md',
  signatoryName: 'Mohan Jha',
  signatoryDesignation: 'Commercial & Technical Operations',
};

export function generateSampleQuotations(): Quotation[] {
  return [];
}
